### PR TITLE
Bug/1686/labels placed incorrecly on delta maps that share no common nodes

### PR DESCRIPTION
**Pull request by RomanenkoVladimir**
# Fix incorrect label placement for delta maps that share no common nodes

_**Please read the [CONTRIBUTING.md](https://github.com/MaibornWolff/codecharta/blob/main/CONTRIBUTING.md) before opening a PR.**_

closes: #1686 

## Description

The issue seems to be that when the two maps share no nodes the deltaHeight was calculated too early, before it is scaled down to 500(the highest height is always 500 in CodeCharta). I moved it from the render service, because when accesing it directly we could run into ThreeJS crashes due to the values not being avalible.

**Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?

## Screenshots or gifs
correctDeltaHeight

### CODE REVIEW

**Review by BridgeAR — COMMENTED** [review]
Does this still work as expected while showing multiple labels at a time? :-) E.g., 10 labels? It seems like the implementation would now use different "stages" depending on what label was first in the list and if it's a low label, it would be lower than later ones that are placed higher?

**Comment by RomanenkoVladimir** [comment]
No, the list is always sorted, starting with the biggest element.
The stages are only relevant for the case that we draw a temporary label.

**Review by BridgeAR — APPROVED** [review]
RSLGTM

**Review by ce-bo — APPROVED** [review]
LGTM - I tested it locally :)

**Pull request merged**
