### PR TITLE
Tech/835/Add issue templates

### LINKED ISSUE #835: Using individual github templates
# Feature request

## Description

It is possible to let github know about different issue templates. That way it's easier for new issues to choose what applies to them.

See https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository.

It is even possible to redirect to other pages, if required. To see this in action: https://github.com/nodejs/node/issues/new/choose

### PR DESCRIPTION
**Pull request by alschmut**
# Tech/835/Add issue templates 

closes #835 

## Description

- Add issue templates like @BridgeAR suggested.
- When you click to create a new issue you will now see the following three options, which will redirect you to the specific issue template
- I added some more sections for the feature-request template

## Screenshots
image

### CODE REVIEW

**Comment by NearW** [comment]
Why do the filenames start with --- ? I couldn't find any convention for that online.

How did you test that locally without merging?

**Comment by alschmut** [comment]
@NearW I was creating them with the GitHub UI 
Go to Tab: Settings > Scroll: Features > Issues > Set up templates
Or: https://github.com/MaibornWolff/codecharta/settings

I didn't test it, I was doing it all through the Browser and then it asked me to commit onto master or create a branch with PR for it.

**Comment by NearW** [comment]
Oh, I see. I didn't know they provide such an easy interface for that. It will be alright then, I guess. :D

**Comment by alschmut** [comment]
After I was just testing the creation of those templates on another project, I will merge these changes now. @fatihi if you still want to adapt the templates, just adjust them within the [Features > Issues > Set up templates](https://github.com/MaibornWolff/codecharta/settings)

**Pull request merged**
