### PR TITLE
Feature/696/redesign metric values

### LINKED ISSUE #696: Metric values can overlap metric names
# Feature request

Metric values can grow quite large. The lines of code especially can reach 20 million lines on larger maps. Currently CodeCharta grows the space for metric values a bit, but larger values are still clipped:

Metric-Value-Current

## Description

How about we let the metric values overlay the metric names? While hovering we don't need to change the metric names anyway. Then we also don't need the dash when nothing is hovered. I suggest we add a grey box around the metric values (a bit like our scenario button). That should also make the metric values changing much more obvious. 

After, when not hovering

After, when hovering
Metric-Value

We can also change the color for positive, negative deltas. For this mockup I put the delta metric on top of the current metric to make it clear that they are related:

Metric-Value-Delta

The visualization should look like the one from #735

### LINKED ISSUE #756: Different text size in dropdown menu
# Bug

## Expected Behavior
Both dropdowns should have the same text styling

## Actual Behavior
Dropdowns have different text stylings

### Screenshots

Screen Shot 2019-10-18 at 09 26 20
Screen Shot 2019-10-18 at 09 26 26

Which one do we prefer here? @fatihi

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/696/redesign metric values

closes #696 
closes #756

## Description

- New style for hovered metric values
- Redesigned slider labels in ribbonBar sections
- Shortened ribbonBar sections

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by NearW** [comment]
I personally think that the color of the delta values should be the same as those for the building (more saturated, I guess?)

**Comment by alschmut** [comment]
@NearW I just used the same color as the building does and it looked way too dark, but we can slightly darken it like on the next gif

Before


After

**Comment by NearW** [comment]
> I just used the same color as the building does and it looked way too dark, but we can slightly darken it like on the next gif

Ah, I understand now and can imagine. Let's keep it this way then.

**Comment by alschmut** [comment]
@NearW I didn't commit this mentioned color change, because you merged the branch already. So I guess the brighter color was fine?

**Pull request merged**
