### PR TITLE
Docs/2949/rewrite docs for using sonarqube

### PR DESCRIPTION
**Pull request by Chrisp485**
# Rewriting documentation for the usage of SonarQube

Closes: #2949

### CODE REVIEW

**Review by MW-Friedrich — COMMENTED** [review]
LGTM!
I think we should be aware of the added effort of maintaining the separate SonarQube Tutorial specific to our project. If SonarQube updates to a new version, we will probably need to update our tutorial as well. Maybe just linking to the https://docs.sonarqube.org/latest/setup/get-started-2-minutes/ tutorial would be enough?
But I am not too deep in the topic unfortunately, has @ce-bo commented on this maybe and I just forgot?

**Comment by Hall-Ma** [comment]
> LGTM! I think we should be aware of the added effort of maintaining the separate SonarQube Tutorial specific to our project. If SonarQube updates to a new version, we will probably need to update our tutorial as well. Maybe just linking to the https://docs.sonarqube.org/latest/setup/get-started-2-minutes/ tutorial would be enough? But I am not too deep in the topic unfortunately, has @ce-bo commented on this maybe and I just forgot?

We already discussed it. And I agree with you, it's also a possible solution but we chose to deliver more detailed instruction to provide easier access with SonarQube for the user (but also with all disadvantages in terms of maintainability).

**Comment by MW-Friedrich** [comment]
> > LGTM! I think we should be aware of the added effort of maintaining the separate SonarQube Tutorial specific to our project. If SonarQube updates to a new version, we will probably need to update our tutorial as well. Maybe just linking to the https://docs.sonarqube.org/latest/setup/get-started-2-minutes/ tutorial would be enough? But I am not too deep in the topic unfortunately, has @ce-bo commented on this maybe and I just forgot?
> 
> We already discussed it. And I agree with you, it's also a possible solution but we chose to deliver more detailed instruction to provide easier access with SonarQube for the user (but also with all disadvantages in terms of maintainability).

Ah I see, thank you!

**Review by MW-Friedrich — APPROVED** [review]
🚀 LGTM!

**Comment by Hall-Ma** [comment]
Please don't merge until @LuisGuenther has given me feedback on the instructions (Beginner's Guide).

**Pull request merged**
