### PR TITLE
Feature/file-panel-delta-label

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/file-panel-delta-label

improves #525 

## Description

- Add `old:` and `new:` labels in front of the delta file-selectors

Screenshot 2019-06-24 at 02 47 11

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [ ] **All** requirements mentioned in the issue are implemented
- [ ] Does match the Code of Conduct and the Contribution file
- [ ] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [ ] **Update the README.md** with any changes/additions made
- [ ] **Update the CHANGELOG.md** with any changes/additions made
- [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [ ] **All tests pass**
- [ ] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [ ] **Manual testing** did not fail

### CODE REVIEW

**Comment by Richargh** [comment]
Are you sure about this PR? The current CC has `file` and `compare` which we debated about for ages. If a building existed in `file` but was missing in `compare` it was displayed as red.

**Comment by alschmut** [comment]
- the intention for this PR was more having at all
- If everybody wants to keep the labels file and compare that's fine
- but to be honest with those labels it's not clear, which is the old version and which is the new one, when you ask a person who never used CC.
- Old and new is even easy to understand for children.

**Comment by NearW** [comment]
But didn't we want to keep our visualization generic? old and new means, that there are two maps of two different timestamps. `Reference` and `Comparison` is more generic.
We could use `From` and `To` as well

**Comment by alschmut** [comment]
`Reference` and `Comparison` are the technical terms, but from a user perspective `Reference` is not intuitive.
-> I actually like `from:` and `to:` 👍

**Comment by Richargh** [comment]
> * but to be honest with those labels it's not clear, which is the old version and which is the new one, when you ask a person who never used CC.

That is the most important question to solve. I like the label idea but we have to make clear what buildings are the baseline=grey and what buildings are the delta=color. Any label you pick that is clear in that regard is fine by me.

**Comment by Richargh** [comment]
I know how to do it: don't use labels at all, use `pictogramms`. The left file picker gets the grey box, representing the grey baseline building. The right one gets the green/red delta building. There are small `+` and + `-` next to them. Green/red have to switch if you invert colors. 

59985721-1f09b200-962b-11e9-97de-6e58be127491

What do you think?

**Comment by NearW** [comment]
@Richargh I like it!

**Comment by alschmut** [comment]
Yea I am not 100% convinced yet,but that might change when I see it implemented ;)

**Comment by Richargh** [comment]
> Yea I am not 100% convinced yet,but that might change when I see it implemented ;)

I am confident. But who implements this now and is it part of this PR?

**Comment by alschmut** [comment]
yea, thats the only thing we are doing for this PR. I will start implementing it

**Comment by alschmut** [comment]
Any ideas, how we could name the image/delta/file-selector/label?

**Comment by alschmut** [comment]
We will create a new branch based on the issue #615 to implement the new ideas. So we can close this PR.

**Pull request closed without merging**
