### PR TITLE
Refactor/2318/migrate color settings panel

### LINKED ISSUE #2876: Reset colors in delta mode doesn't work
# Bug

When in Delta Mode, and you change the colors and afterwards want to reset to default, only the selected color gets reset. Positive + negative delta dont get reset.

## Screenshots
image

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.99.1

### PR DESCRIPTION
**Pull request by shaman-apprentice**
This PR does:
- migrate color settings panel
- fix #2876

### CODE REVIEW

**Comment by shaman-apprentice** [comment]
I noticed a small bug, which is already in current version (https://github.com/MaibornWolff/codecharta/issues/2874). I likely introduced it in a previous PR and will fix it in a separate PR.

**Review by Chrisp485 — COMMENTED** [review]
@shaman-apprentice When in Delta Mode, and you change the colors and afterwards want to reset to default, only the selected color gets reset. Positive + negative delta dont get reset.
delta_color_reset

**Comment by shaman-apprentice** [comment]
> @shaman-apprentice When in Delta Mode, and you change the colors and afterwards want to reset to default, only the selected color gets reset. Positive + negative delta dont get reset. delta_color_reset

Thanks, good catch! Although this is a bug not related to the migration. I just created #2876 and fixed it within this migration PR.

**Review by Chrisp485 — APPROVED** [review]
LGTM, bug is fixed thanks 👍

**Pull request merged**
