### PR TITLE
Bug/857/Loading Gif not displayed when preparing to render a new map

### LINKED ISSUE #857: Loading GIF not displayed on current master
# Bug

## Expected Behavior
The loading GIF should appear if an action takes longer

## Actual Behavior
It does not appear

## Steps to Reproduce the Problem

  1. Load large map (e.g. Amazon)
  1. Switch to delta mode
  1. Loading gif does not appear

## Specifications

  - Version: current master (1.42)
  - Platform: Windows
  - Subsystem: 10
  - Browser: Firefox

### PR DESCRIPTION
**Pull request by NearW**
# Loading Gif not displayed when preparing to render a new map

closes #857

## Description

- Refactored the way we set the flag for preparing a new map to render
- Renamed the methods to suite a more business logical term

**Needs Investigation:**
~Everything is working as it should. The flags are being set and cleared correctly at the right moment and the subscribers (loadingGifController) is receiving the flag-changes. HOWEVER, for some reason the gif is not displayed and I can't find out why this is the case. Can someone look into this branch for a 15min timebox and try to figure out a mistake I may not see?~

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
I just compared the master and this branch and in my opinion the loadingGif shows up a lot better than before. It might not show up for the sample maps, as they are quite small and fast to render, but for every other larger maps or many maps together, it was showing the gif as expected (:

**Comment by NearW** [comment]
> I used the Browser Safari with the sample maps, some codecharta maps, the Firefox and amazonaws maps.

The loading file is displayed but the loading map gif in the top right corner is missing completely for me in chrome AND safari.

**Comment by alschmut** [comment]
@NearW it seems the UI freezes for a few milliseconds and can not update the components in between..

**Comment by NearW** [comment]
Fixed the issue.

**Pull request merged**
