### PR TITLE
Fix/2498/remove example maps

### PR DESCRIPTION
**Pull request by BenediktMehl**
# remove example maps

Closes: #2498 

## Description

If there are sample files loaded as fallback maps when starting the application,
then those files are removed as soon as the user uploads own files.

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
- [ ] Changes have been manually tested
- [ ] All TODOs related to this PR have been closed
- [ ] There are automated tests for newly written code and bug fixes
- [ ] All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
- [ ] Documentation (GH-pages, analysis/visualization READMEs, parser READMEs, --help, etc.) has been updated (almost always necessary except for bug fixes)
- [ ] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by phanlezz** [comment]
Clearing webstorage war required. #3641.

**Comment by phanlezz** [comment]
Currently clears sample1,sample2 when opening dev/standalone. Does not clear default maps when opening webdemo.
I think that behavior is good. What do you think @ChristianHuehn ?

**Comment by CodeCharta** [comment]
Nah it should also delete them on the webdemo. 

In general we just want to get the following:
- Person opens web demo
- Sees CodeCharta with Analaysis and Visualization
- uploads his own maps
- Visualization and analysis should be removed as they want to focus on the stuff that they uploaded

To make this easier we should probably just remove the maps from the url query parameters once

**Comment by BenediktMehl** [comment]
> To make this easier we should probably just remove the maps from the url query parameters once

Fixed the issue without addressing the removal of the URL parameter "file". I think this should be a new issue, since currently the URL parameter "file" is only related with the shown maps on initial loading of the site.

**Review by phanlezz — APPROVED** [review]

**Pull request merged**
