### PR TITLE
Feature/273/enhance focusing nodes

### LINKED ISSUE #273: Redo Isolating nodes
# Feature request

Regarding what @Richargh mentioned in #268 

## Description

I think we should change how isolate works from a user perspective. 
- Let's rename `Isolate` in the context menu to `Focus`. 
- Then If you have focused on something a button appears in the bottom right corner (where it fits) `Show Complete Map`. If you click on it, it shows you the complete map. All the while, the items in your blacklist that are hidden are not touched at all. So if you click on `Show Complete Map` it won't change the items that are declared as `hide`. No matter what we do with `Focus` the cc.json does not need to be modified.
- Remove `Show All` from context menu.

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/273/enhance focusing nodes

Connects #273 Closes #273 

### Added
- Button appears on the bottom right corner to `unfocus` the node, when a node is on focus
- NodeContextMenu: Option to only hide dependent edges (not issue related, but was a convenient small change)
- 95% test-coverage for `codeMap.actions.service.ts`

 ### Changed
- Refactored `Isolate node` to `Focus node`
- Focusing a node does not remove the blacklist items of type Hide or Exclude
- Refactored a lot inside `codeMap.actions.service.ts`

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [x] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [x] Task has its own **GitHub issue** (something it is solving)
  * [x] Issue number is **included in the commit messages** for traceability
* [x] **Update the README.md** with any changes/additions made
* [x] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [x] **All tests pass**    
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [ ] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
Does anybody have a clue about why the travis PR build fails after merging the master into it?

**Comment by FernandoES** [comment]
Travis found some problems by finding some node modules.

I have a suggestion, I would consider that once "focused" the command "show all" found when right clicking should have the same effect that "unfocus" has.

Appart from that, everything is ok, so once done this two changes I would merge it

**Comment by alschmut** [comment]
The functionality is kinda different:
Show all:  Unhides all previous hidden nodes
Unfocus: Show the complete map but hide and exclude blacklisted nodes

But, we can discuss a renaming of `show all` to `unhide all`

**Comment by FernandoES** [comment]
I see, that makes sense then, I would agree with the rename you purpose

**Comment by FernandoES** [comment]
I would also suggest to have unfocus in the same right click menu that the other options, for having all the similar option in the same list

**Comment by FernandoES** [comment]
The start of the failure makes no sense, since the merge was really small and changed no dependency or import at all.

It crash when running travis-build.sh, in the last command. I ran this command on local and works properly , so I can not reproduce the failure.

**Comment by FernandoES** [comment]
Originally the travis problem with node dependencies appeared in a simple merge from master (one .html file and its scss), so I undid this change and did it step by step. The only step that produced problems was the last one, adding 5 empty spaces on the left of a html text. I really do not know how that can ocasionare a dependency problem, but deleting those spaces solves the problem. 

Once that we discuss the renaming and potential moving of the button I would suggest tu merge this pull request

**Comment by mrpatpat** [comment]
> Does anybody see, why the travis-ci/push failed again? I would really like to know, what I did wrong on this branch..

We had this problem, too. Restarting the build helped. I will look into it tomorrow and if it is something serious, create a bug report.

**Pull request merged**
