### PR TITLE
Tech/826/replace tslint with eslint

### LINKED ISSUE #826: TSLint: new rule prefer-const
Add and test this rule: https://palantir.github.io/tslint/rules/prefer-const/

### PR DESCRIPTION
**Pull request by alschmut**
# Tech/826/replace tslint with eslint

## Description

- Replaced TSLint with ESLint
- ESLint config created and adapted by [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config)
- Added prettier extension in eslint config [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) so that eslint doesn't overwrite prettier rules
- Added [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) to prettify when linting
- Added needed public modifier to comply with all given rules

## TODO
- I didn't add the [`prefer-const`](https://eslint.org/docs/rules/prefer-const) rule yet, as I suggest to first merge some other rather large PRs.
- We can also check [recommended-configs](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs), but those come with more rules, we don't use yet, so we would need to spend a bit more time to fix our code (and mostly merge with other branches)

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by NearW** [comment]
Is the prettier extension really required? I see a problem with only linting .ts-files and therefore only formatting ts-files while before we formatted EVERY file.

I'd suggest to remove the formatting from eslint and keep it separately as we did before with pretty:quick

**Comment by alschmut** [comment]
Sure, we can leave out formatting within eslint, but I would keep the eslint-config-prettier, as it ensures eslint is not formatting code differently than our prettier.

We actually only listed ts files before either: [see](https://github.com/MaibornWolff/codecharta/pull/873/files#diff-446c5d0d2cc4f63612017de871c480f2R73) the `.ts` ending

**Comment by NearW** [comment]
> Sure, we can leave out formatting within eslint, but I would keep the eslint-config-prettier, as it ensures eslint is not formatting code differently than our prettier.

Are you sure that eslint formats automatically? I think you have to tell him in the CLI with `-f` to do so. You can even select the formatter with that.

I just removed eslint-config-prettier completly and it's not formatting when linting at all now. After that, we do our format:quick script anyway. :)

**Comment by NearW** [comment]
also removed the tslint config

**Comment by alschmut** [comment]
Rules might currently not conflict, but when they do, we will need the eslint-config-prettier again ;)

**Pull request merged**
