### PR TITLE
Feature/1066/display tooltip description on metic chooser

### PR DESCRIPTION
**Pull request by BenediktMehl**
# display tooltip description on metic chooser

Close: #1066 

## Description
The new attribute titles are shown by the metric choosers. 
The search-field searches for names and titles. 
Below are some different versions to choose from:

## VERSION 1 (this is the current state of this branch):

The titles are shown.
The names and descriptions are shown when the metric is hovered.
- Simple and good looking solution.

Screenshot 2022-12-07 at 13 54 01

## VERSION 2:

The titles AND names are shown.
The names and descriptions are shown when the metric is hovered.
- Good for old users only knowing the names.
- Some of the names are too long to be fully shown.

Screenshot 2022-12-07 at 13 56 44

## VERSION 3:

The titles are shown.
The names are shown smaller below the titles
The names and descriptions are shown when the metric is hovered.
- Looks good and is good for old users.
- Still unclear how it should look, when search is collapsed.
- This would be much more work. The image below is just made with powerpoint

Screenshot 2022-12-07 at 14 13 52

### CODE REVIEW

**Comment by BenediktMehl** [comment]
In the retro from 8.12.22 we decided to go with Version 3, but the names (now named keys) are swapped with the titles.
- Keys and values are shown like before.
- Titles are shown smaller and in the color of the values in the line below.
- The tooltip includes all attributeDescriptor agruments (title, description, hintLow, hintHigh, Link)

**Comment by ce-bo** [comment]
The tooltip includes metric title, description, hintLow and hintHigh. The link should also appear in the near of every select item. Idea: Show External Link Icon for every select item.

**Comment by BridgeAR** [comment]
Could this be taken by someone from the team? :-)

**Comment by MW-Friedrich** [comment]
I'm on it and already working on a solution. I will open a new branch for it though when I have something to show.

**Pull request closed without merging**
