### PR TITLE
Feature/add temporal coupling in visualization

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/add temporal coupling in visualization

## Description

This PR adds the option to visualize the temporal coupling data, which can be imported with the new CodeMaat-CouplingImport.

1. There is a new Temporal Coupling Panel with a list of the dependency couples in the settings sidebar
2. Every Couple has a number of shared commits and a relative number "Pairingrate", which gives you information about the percentage of coupling.
    - When hovering the list item a tooltip/title shows expanded information and the full filepath
3. To adjust the list with Couples there are different settings:
    - Slider: set minimum number of shared commits
    - Checkbox: Use Pairingrate Height (or use metric from Metric Chooser)
    - Checkbox: "Intelligent" Filter to remove couples, like `*.log`, `build.gradle` or `CHANGELOG*` etc. (This Filter has a lot of potential for future improvements)
    - Checkbox: Show Connections turns the connecting arrows on and off
4. The TC list always syncs with the CodeMap and only shows the couples, when both nodes are visible inside the CodeMap
5. To try out the visualization without having to import the couples before, two test files ([codecharta.json](https://github.com/MaibornWolff/codecharta/blob/feature/add-temporal-coupling-visualization/analysis/test/data/codecharta/codecharta.json) and [git.json](https://github.com/MaibornWolff/codecharta/blob/feature/add-temporal-coupling-visualization/analysis/test/data/codecharta/git.json)) are added inside the directory `/analysis/test/data/codecharta/...`

- The [cc.json](https://github.com/MaibornWolff/codecharta/blob/feature/add-temporal-coupling-visualization/visualization/app/codeCharta/core/data/schema.json) schema of course needed to change. It is now the same as the one inside the Validation Tool! The `/codecharta/cc.json` file has been removed, because of duplicated file content.
- I updated a lot of tests with its test json data and usually only added `type` and `dependencies`

bildschirmfoto 2018-08-06 um 13 19 02

bildschirmfoto 2018-08-06 um 13 02 28

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [ ] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [ ] Task has its own **GitHub issue** (something it is solving)
  * [ ] Issue number is **included in the commit messages** for traceability
* [x] **Update the README.md** with any changes/additions made
* [x] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [ ] **All tests pass**    
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [x] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by ukinimod** [comment]
I will do a more systematic code review later, first some comments:
- I like the ability to be able to visualize temporal coupling (or coupling in general) in codecharta.
- I like the temporal coupling tab in the sense that it lists the hotspot dependencies. I can figure using this in audits to find strange dependencies and highlight them in a presentation.
- I guess this feature is not compatible with aggregation and delta.
- Filtering unnecessary files could be done in a different way, e.g. filtering when generating the log, filtering in the csv, filtering the uninteresting nodes and only show dependencies for visible nodes. I think adding the "intelligent filter" with hardcoded values could be removed before merging.
- Personally I would map the pairing rate to the colour. I find this more intuitive than the height. Furthermore I don`t figure displaying hierarchy, coupling and three metrics at the same time is really necessary (yes, I'm always for a minimal necessary feature set), therefore this feature could imho be deleted.
- average-revs sind NICHT die gemeinsamen Commits sondern der Durchschnitt der Commits.

Detailed review later...

**Comment by alschmut** [comment]
Thanks as well for your feedback!

3. At the moment it is not compatible with aggregation and delta. Aggregation can be implemented as a simple aggregation of both dependency lists, but to get dependencies with nodes from different original projects, we need to try to combine the log files and analyze those. Although files from different projects will (I think so) never be in the same commit. But CodeMaat also allows the connection of files by the day (when the commit was made) instead of the commit itself.
4. Okey I agree with the filter. This will then be implemented with #181.
5. The problem with using the normal chosen metric is, that some buildings might be very small and the User can't see them on first sight. But to mention that: I also thought about the idea to color all other buildings in a light gray. Then the colored coupled buildings get highlighted again even more. @ukinimod sorry, I couldn't follow which feature you wanted to be deleted.
6. Oh, so i misunderstood that, thanks.

**Comment by alschmut** [comment]
7. Yes it filters the list by AverageRevs.
8. Okay, it actually were nice to put the new `edges.attributes[]` inside the existing metric-chooser. Maybe at the top or bottom of the select-list and marked as edge-metric.
9. I have added the "intelligent filter", because sometimes many log and gradle files occurred in the top 10 couples, but as @ukinimod said, we should better exclude files inside the analysis.

10/11/12/13. Yes, we can implement something like this to improve usability afterwards :)

**Comment by ukinimod** [comment]
It's probably only vaguely related to this pr, but I guess this context is good enough.

what I, and some collegues talked about, would find very interesting (mostly in the analysis use case) to be able to display the (especially temporal) coupling for certain hotspots. I'm not quite able to put it in good words, but I would describe it as the degree the "foulness" of this class / file is spread across the project. 

One possible visualization that we discussed for this, is a way to select the file, that is considered as hotspot. Then something like the pairing rate for all (temporal) coupled (with a possibly configurable limit) are coloured by their degree (e.g. pairing rate) of dependency.

**Comment by alschmut** [comment]
I have opened new issues from all your comments to work on those before merging into master

**Pull request closed without merging**
