### PR TITLE
Feature/714/add-autocompletion-for-ccsh

### PR DESCRIPTION
**Pull request by ce-bo**
# Add Bash TAB Autocompletion for ccsh command

_**Please read the [CONTRIBUTING.md](https://github.com/MaibornWolff/codecharta/blob/main/CONTRIBUTING.md) before opening a PR.**_

Fixes: #714 

## Description
Picocli can generate auto-complete scripts for Bash or Zsh. To make ccsh easier to use we should also generate and distribute these scripts.

**Descriptive pull request text**:
  - This PR will introduce a new ccsh option to generate the completion script on demand.
  - Using source command, the completion script can be activated in Bash.
     source <(./bin/ccsh generate-completion)

## Screenshots or gifs
How to use autocompletion:
picocli-autocompletion-demo
Gif from PicoCLI: https://picocli.info/images/picocli-autocompletion-demo.gif

### CODE REVIEW

**Review by BridgeAR — APPROVED** [review]
RSLGTM

**Comment by BridgeAR** [comment]
@ce-bo would you be so kind and open a new issue for a plop implementation that is triggered if no arguments are passed to the `ccsh` binary?

**Comment by NearW** [comment]
So this is something the user has to enable by himself?
Isn't it possible to execute this command automatically, when installing the analysis from npm?
And can this be enabled automatically for the the release-packages we distribute?

**Comment by ce-bo** [comment]
@BridgeAR would it be possible to run `source <(./bin/ccsh generate-completion)` within `npm i -g codecharta-analysis` using a npm "postinstall" script?

**Comment by BridgeAR** [comment]
An sich wäre das möglich. Es kann aber sein, dass wir sudo Berechtigungen benötigen und das ganze funktioniert halt auch nicht in allen terminals. Das müsste daher graceful implementiert werden (keine Fehlermeldung im Falle eines Fehlers).

**Pull request merged**
