### PR TITLE
Feature/640/move detail panel

### LINKED ISSUE #640: Move the file path and detail panel to the top
# Feature request

CodeCharta currently shows the file path and the detail panel in the bottom left corner, when hovering. 

## Description

Please move it to the top left, so it's close to the metrics. Let's move it to the right if the search panel is open, so it's not visually blocked by the panel. The metric ribbon can overlay it.

### PR DESCRIPTION
**Pull request by alexhunziker**
# Move DetailPanel to top-right

closes #640 

## Description

- Moved DetailPanel to the top-right and the ViewCube to bottom-right

grafik

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [ ] **All** requirements mentioned in the issue are implemented
- [ ] Does match the Code of Conduct and the Contribution file
- [ ] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [ ] **Update the README.md** with any changes/additions made
- [ ] **Update the CHANGELOG.md** with any changes/additions made
- [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [ ] **All tests pass**
- [ ] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [ ] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
So, the code is fine 👍 But to be honest, I really don't like the detailPanel up there. @Richargh as it was your suggestions, would you like to take a look as well? It just feels wrong, especially when open the metric sections and the legend panel.

Depending on how many user actually open the detail panel, I am fine with this temporary solution, but we really need to invest in #527 

image

**Comment by fatihi** [comment]
You are right, but it depends on if people leave the metrics open or not, for that we would have to ask some users. Maybe there isn't a need to change the metrics and see the details at the same time. 
I suggest we leave it there right now and I'll ask for some feedback.

**Comment by Richargh** [comment]
@alschmut sigh, you are right. @alexhunziker sorry for wasting your time as well. 

I pushed this feature because I wanted all things to finally be like our UI mockup. **Let's drop this pull request and do it correctly.** Is that ok with you two? 

First we need the new side bar #527 then we move the path indicator with #607

**Comment by alexhunziker** [comment]
@Richargh yes, closing this PR is fine for me. The only benefit i see from this modification here is that it draws more attention to the availability of the detail panel, but I agree with @alschmut that it does not look that great.

**Comment by Richargh** [comment]
@alschmut @fatihi and @alexhunziker I updated the description and screenshot of #527 and #607 and I quite like the result. Please take a look :)

**Comment by Richargh** [comment]
Should we close this issue and pr?

**Comment by fatihi** [comment]
Oh sorry I thought you did already ^^

**Pull request closed without merging**
