### PR TITLE
adding coloured delta to quickAccess panel

### PR DESCRIPTION
**Pull request by FernandoES**
## Description

Deltas added to the metric quick access panel on the top of the website. (Issue #138 )

When deltas are activated the selection box of deltas substitute the selection boxes of heigh and color metric, which disappear. When deltas are deactivated heigh and color metric boxes appear again and delta box disappear.

if the delta is 0 a black 0 value is shown, if positive a red value following a green + is shown, and for negative values both a - and the value are shown in red.

The color is applied in the text instead in the background because the effect in the background was not considered nice, see picture below:
bildschirmfoto 2018-05-31 um 11 29 17

The color is chosen with the html tag style color instead of md-color because the right color was not found in md-color (see red in the upper picture compared to the pictures below). 

Panel when deltas is deactivated:
bildschirmfoto 2018-05-31 um 12 35 41

Panel with a delta of 0:
bildschirmfoto 2018-05-31 um 12 39 35

positive delta:
bildschirmfoto 2018-05-31 um 11 58 50

and negative delta:
bildschirmfoto 2018-05-31 um 11 58 42

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [x] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [x] Task has its own **GitHub issue** (something it is solving)
  * [x] Issue number is **included in the commit messages** for traceability
* [x] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [x] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
@mrpatpat @Richargh check out the new commit (: it even adapts the colour when flippedDeltaColor is activated. Although I know the static colors "green" and "red" might change during the next few weeks.

**Comment by mrpatpat** [comment]
Looks good !

**Comment by FernandoES** [comment]
Some changes done to meet expectations:
 - delta is shown in the three metrics ( color, height and area) but only show color in height.
- Detail panel minimized by default

@Richargh please have a look

**Comment by alschmut** [comment]
Question @mrpatpat @Richargh @FernandoES : Do we want to show the values (inside metric chooser and path for minimized detailPanel) of the selected building when no building is hovered?

**Pull request merged**
