### PR TITLE
Feature/780/treeview click events

### LINKED ISSUE #780: Replace unexpected click-events in Treeview list
# Feature request

## Description

While working on #380 I remembered that I was once talking with @NearW about a treeview list feature redesign. Currently we provide following functionality
- onclick eye-icon: hide the node
- onclick slashed-eye-icon: reshow the node
- onclick node-name: focus node

In my opinion applications handle such actions differently:
- All of those actions can be managed inside the already existing context-menu, when right clicking the list item, which makes them all redundant
- Therefore I suggest to show the three dots icon on the right of a hovered list item, which indicates, there are more options, when the user presses these dots (`fa-ellipsis-h`-icon). This then opens the same context menu, as if the user had used the right click.
- Moreover, focusing the node, when clicking its name is some very weird behaviour, which confuses me every time I accidentally press the name
- In my opinion we should also consider removing the eye icon at all to gain more clarity/simplicity and just cross out the node name or color it in light grey.
- Since we implemented the attribute side with #527 I feel like clicking the codename, should rather select the hovered node, which in turn opens the attributeSide bar etc.

(the screenshot is taken from the current branch of #380)

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/780/treeview click events

closes #780

## Description

- Added ellipsis button in TreeView list when hovering a node to access context menu
- Added gray flattened-symbol next to the ellipsis-button to indicate a flattened node (only visible when hovered)
- Changed showing absolute number of files instead of relative number when hovering list item in TreeView
- Changed clicking a hovered list item inside the TreeView opens folders
- Changed color node name in gray when flattened
- Removed eye-icon in TreeView list to flatten a node
- Removed option to focus a node when clicking the node name inside the TreeView

### Side note
- Right clicking the list item still opens the contextMenu as well
- When a flattened node is searched, it is coloured green

### After
normal/hovered

searched for `*.ts` + normal/hovered

gif

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [ ] **All** requirements mentioned in the issue are implemented
- [ ] Does match the Code of Conduct and the Contribution file
- [ ] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [ ] **Update the README.md** with any changes/additions made
- [ ] **Update the CHANGELOG.md** with any changes/additions made
- [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [ ] **All tests pass**
- [ ] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [ ] **Manual testing** did not fail

### CODE REVIEW

**Comment by Richargh** [comment]
Love the changes, especially:

> Changed clicking a hovered list item inside the TreeView opens folders

Awesome! I'm not sure about the strike through though. That makes somewhat sense for excluded items but flattened items are still there right, so striking through them is strange, isn't it?

**Comment by alschmut** [comment]
Thanks @Richargh!

That’s a good point regarding the cross out. Excluded nodes don’t show up in the treeView. Flattened nodes do though. Maybe only coloring those in gray is enough? (Keep in mind that searched nodes are colored in green)

**Comment by Richargh** [comment]
Maybe gray+show the flattened symbol next to three dots? 

Also can you search for flattened nodes? In the 1.44.0 you can. If so what is the color of searched + flattened nodes? Maybe still the same green because you have the flattened symbol as well?

**Comment by alschmut** [comment]
@Richargh that is an idea. As I kinda wanna keep the treeView clean and the node-name is coloured gray (when the node is not searched), I suggest to only show the flattened-symbol when hovering. See example below.

**Comment by Richargh** [comment]
Ok by me :)

**Comment by alschmut** [comment]
I just updated the PR description including new screenshots and a new gif

**Comment by NearW** [comment]
@alschmut conflicts

**Comment by NearW** [comment]
When you have a huge map and want to select a specific building that you have in your treeView, you have to check where it is on the map and select it there.

I think it would be good to be able to select buildings from the treeView as well. Clicking on it will open the folder now, so maybe we could add a double click to select it?

**Comment by alschmut** [comment]
@NearW yea that is a possible addition, though I would suggest to create another issue for that and merge this PR.

**Pull request merged**
