### PR TITLE
Refactor/3250/ngrx

### LINKED ISSUE #3250: Migrate redux to NgRx
# Maintenance

As a developer I don't want to mix different libraries and best practices, so that I can easily read existing code and need only one mindset for writing new code.

In [ADR 8 angular migration](https://maibornwolff.github.io/codecharta/adr/ADR_8_angular_migration/) we decided to use [rxjs observerables](https://rxjs.dev/guide/observable) and migrate to [@ngrx/store](https://ngrx.io/guide/store).

While migrating from AngularJS to Angular we already introduced an ngrx/store like wrapper around redux [here](https://github.com/MaibornWolff/codecharta/blob/main/visualization/app/codeCharta/state/store/store.ts). For completing this transition we want to replace redux and this wrapper through a real  ngrx/store.

## Expected advantages
- We can remove our custom minimal redux to NgRx wrapper. Instead we will have full NgRx API available
- We can use NgRx testing utilities. This enables us for a cleaner mocking of selectors. We can likely reduce how often we initialise the complete store by a lot.
- NgRx has better typings
- NgRx boilder code is less verbose than redux's

## Acceptance criteria
- `redux` is replaced from package.json

## Development notes (optional Task Breakdown)
- [x] Replace redux store through ngrx/store. This includes rewriting all actions and reducers.
- [x] Replace custom selectors through real selectors.
- [x] Replace custom effects through real effects.
- [x] Adjust tests

### LINKED ISSUE #3268: Delta Mode not working anymore
# Bug

The delta mode does not show any deltas anymore

## Expected Behavior

<GIVEN>

WHEN
loading two maps in delta mode

THEN
there should be deltas even if the two cards do not share any code files

## Actual Behavior
no deltas are shown.

## Screenshots
image

## Steps to Reproduce the Problem
1. Open Web Demo
1. Switch to delta mode
1. select comparison file

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.115.1
- OS: Windows
- Browser: Chrome

### PR DESCRIPTION
**Pull request by shaman-apprentice**
- replace redux through ngrx
- fix at least one broken memorization leading to a lot of unnecessary calculations
- Code Smells are copied over todos which already existed before and not related to changes from this PR

close #3250 
fix #3268 (which was probably caused by racing conditions)

### CODE REVIEW

**Comment by phanlezz** [comment]
I did some manuel testing:
The bug mentioned in #3268 seems to be resolved by this pr.
Completly different maps with the same metrics are again displayed in red/green:
grafik
Previously tested cc99 and cc105 show differences correctly:
grafik

A little bug, where I'm not sure if it is new, is that red colored buildings are never completly red, as there are supposed to be, instead always have a gray part at the bottom. I'm not sure if this is intended or not. Green buildings can be completly green.

Buildings keep their 'selected' color orange in delta mode.
grafik


Everythings else looks and feels good 🚀

**Comment by shaman-apprentice** [comment]
> A little bug, where I'm not sure if it is new, is that red colored buildings are never completly red, as there are supposed to be, instead always have a gray part at the bottom. I'm not sure if this is intended or not. Green buildings can be completly green.
> 
> Buildings keep their 'selected' color orange in delta mode.

On current released version, selection doesn't go away in delta mode as well. Red buildings also have a little gray bottom. @ce-bo do we already have a bug for the first one? I am not sure if the second one is a bug.
image

**Comment by Hall-Ma** [comment]
I have manually tested some functionalities, which all work as expected:
- Delta mode including switch maps via the button
- Flattening buildings
- Coloring of folders
- Excluding buildings and folders and then inserting them via the eye button
- All settings in Color Metric Option Settings, Area Metric Option Settings, Height Metric Option Settings
- Show legend and change colors
- Show attribute sidebar and switch median/average via the button
- Load maps via the file chooser
- Rotate maps via the Cube
- Show High-Risk Profile
- Show Suspicious Metrics and select one via button
- Height and Size Metric Link Button
- Search panel (click through the folder structures)
- Change height, area and color metric
- Change map layout, resolution, background and experimental features
- Select buildings/folders on the map
- maps with edges are shown and edges can be deactivated
- add custom view and load custom view via panel

**Comment by Hall-Ma** [comment]
@shaman-apprentice one bug I found was this:
- load sample maps, apply a suspicious metric that is very high risk (exclamation mark button)
- then apply metric template for complexity and the colors do not change
In the demo this use case is working. Maybe you can take a look at it?

Thanks for the ngrx implementation! This was a huuuge job! :heart:

**Comment by shaman-apprentice** [comment]
> @shaman-apprentice one bug I found was this:
> * load sample maps, apply a suspicious metric that is very high risk (exclamation mark button)
> * then apply metric template for complexity and the colors do not change

Good catch. Fixed. I forgot to use default value, when undefined is dispatched. I fixed it for map colors. 

In a future commit I will fix it for every action, which had it previously.

**Review by phanlezz — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
