### PR TITLE
Refactor/2318/migrate metric value hovered component

### PR DESCRIPTION
**Pull request by shaman-apprentice**
- migrate metricType.component
- store hovered node id in store instead of hovered node path, as hovered node path can be easily derived by id but not vice versa
- while refactoring a little I noticed a bug and created #2731. When fixing it, I will refactor a little more

ref #2318

### CODE REVIEW

**Comment by shaman-apprentice** [comment]
The 2 code smells are the typical "redux pattern smells" and actual fine

**Review by Christian-Eberhard — APPROVED** [review]
Should we keep empty files like "visualization/app/codeCharta/ui/metricType/metricType.component.scss" ?

**Comment by shaman-apprentice** [comment]
> Should we keep empty files like "visualization/app/codeCharta/ui/metricType/metricType.component.scss" ?

We shouldn't. And I have removed it, haven't I?

**Comment by Christian-Eberhard** [comment]
I found one file thats new with empty content, -> visualization/app/codeCharta/ui/metricType/metricType.component.scss

**Pull request merged**
