### PR TITLE
Bug/1040/sorting not working

### LINKED ISSUE #1040: Sorting not working
# Bug

## Expected Behavior

GIVEN the search field is open

WHEN clicking on the sorting button

THEN the order changes according to the chosen order

## Actual Behavior

The behavior does not change

## Screenshots

image
image

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

### PR DESCRIPTION
**Pull request by NearW**
# Sorting Option not working without collapsing and reopening the folders

closes #1040 

## Description

- Removes the `track by $index` 

Please don't ask me why this fixes the issue. I have no idea and I accept this black magic.

## Screenshots or gifs

sorting bug

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by BridgeAR** [comment]
Would it actually be much work to add an e2e test for this?

**Comment by NearW** [comment]
> Would it actually be much work to add an e2e test for this?

No. e2e tests would improve our code a lot. I think after adding this e2e test we should consider running e2e tests only on master and not during PRs.

**Comment by alschmut** [comment]
@NearW according to that "sorted" list, I would guess that A-Z comes before a-z. Is that intended? I would expect it to be sorted by alphabet aAbB...zZ.

**Comment by NearW** [comment]
@alschmut Good point. That looks weird and is a bug. Opening an issue for that.

**Pull request merged**
