### PR TITLE
Avoid "From" from being upper than "To" -1 in Color Range

### PR DESCRIPTION
**Pull request by FernandoES**
# Solution for Issue #121

### CODE REVIEW

**Comment by alschmut** [comment]
The slider works almost as expected. It just "crashes" with negative numbers. But the map doesn't adapt the new color range. I thought its because you didn't apply the settings as before `this.settingsService.applySettings(this.settingsService.settings);`, but it didn't work either when calling it. Did you experience the same issue?

**Comment by FernandoES** [comment]
It neither adapt the new color for me, both with the numbers and with the sliders. Previously it didn't adapt it with the colors but it did with the slider. I'm looking for a solution now

**Comment by FernandoES** [comment]
When it comes to negative numbers I check that if I set "to" to 0, "from" is set to -1, in the update the lower value for to will be 1, like it is in the slider. It is not possible for me to input negative numbers, neither typing them or clicking in the reduce button. Does it make sense for some metric to have negative values?

**Comment by FernandoES** [comment]
The new push should solve all the above mentioned problems, by:
 - Set upper and lower limits for "from" and "to" values.
 - added option "onChange" to rzslider as an equivalent for ng-change
- the new methods now call to onSliderChange, previously they called to onToSliderChange by a typo

**Pull request merged**
