### PR TITLE
Feature/306/277/remove-delta-invert-height

### LINKED ISSUE #277: Remove Invert Height option  in Delta Mode
# Bug

The actual behavior detailed below is a bug. Please remove invert height option from delta view. We'll probably not need it.

---------

## Expected Behavior
Assumption: Delta mode and Invert Height are selected
- the overall node height (grey+color) should get inverted
- the split colors grey+green or grey+red should keep the same ratio as before

## Actual Behavior
Assumption: Delta mode and Invert Height are selected
- Only the grey node height gets inverted
- The green or red block is just added on top of the grey node with the same height as before

### Screenshots
Delta Mode, normal Height
 

Delta Mode, Invert Height
 

## Steps to Reproduce the Problem
  1. Open RibbonBar and switch to Delta Mode
  2. Select a second comparison map with different metric-values
  3. Now the map looks as expected
  4. Select `Invert Height` in RibbonBar
  5. Now the map looks kinda weird as the grey boxes get inverted, but the delta boxes above just keep the same height

## Specifications
  - Version: 1.19.0

### LINKED ISSUE #306: Remove `invert height` from delta view
`Invert height` is a feature that leads to problems in the visualization of deltas. 

Say our building used to have 50% code coverage and it now has 80% coverage, positive delta of 30%, visualized as a block on top of the grey building.

The inverted height should now be 20%. But what should the positive delta be? Still 30% for sure but it cannot be a green block on top of the grey building. Should it be a red block now on top of the grey building? 

We'll solve this problem by removing `invert height` from delta view :)

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/306/277/remove-delta-invert-height

closes #306 
closes #277 
## Description

- Remove `Invert Height` checkbox from RibbonBar when codeMap is in `Delta` mode (Don't get confused about changing the position of the `Invert Colors` checkbox into the Height-section)

Single view
image

Delta view
image

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [x] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [x] Task has its own **GitHub issue** (something it is solving)
  * [x] Issue number is **included in the commit messages** for traceability
* [x] **Update the README.md** with any changes/additions made
* [ ] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [x] **All tests pass**    
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [ ] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by mrpatpat** [comment]
This can be merged in my opinion. 

Regarding the color checkbox change: I get why it could technically be placed there. In reality it confuses me since I still associate it with color. 
I do not know if there was some discussion or reason but I would place it in the old position.

**Comment by alschmut** [comment]
> This can be merged in my opinion.
> 
> Regarding the color checkbox change: I get why it could technically be placed there. In reality it confuses me since I still associate it with color.
> I do not know if there was some discussion or reason but I would place it in the old position.

Yea, if I remember right, that was @Richargh idea, but we can talk about that again in our Meeting

**Comment by Richargh** [comment]
If it confuses everyone but me, we should place it in the color area again.

**Comment by alschmut** [comment]
I just changed the position of the `Invert Height` checkbox when `Delta` mode is activated into the `Height` section.

**Pull request merged**
