### PR TITLE
Refactor/2318/migrate presentation mode button

### PR DESCRIPTION
**Pull request by shaman-apprentice**

### CODE REVIEW

**Comment by shaman-apprentice** [comment]
- [ ] add changelog
- [ ] make prettier happy again
- [ ] font and capital as "Global Configuration"

**Comment by BridgeAR** [comment]
Is it intentional that this is still a draft?

**Comment by electricbrick42** [comment]
> Is it intentional that this is still a draft?

@BridgeAR No! Thanks for mentioning. Now it's ready to review.

**Review by shaman-apprentice — COMMENTED** [review]
Be careful to not produce to "Chore" sections in changelog when merging main ;)

LGTM. Thanks for the completion @electricbrick42 ! As I opened this PR for you I cannot approve. Otherwise I would ;) Can you approve for me and merge please? :)

**Comment by electricbrick42** [comment]
> Be careful to not produce to "Chore" sections in changelog when merging main ;)
> 
> LGTM. Thanks for the completion @electricbrick42 ! As I opened this PR for you I cannot approve. Otherwise I would ;) Can you approve for me and merge please? :)

@shaman-apprentice You're welcome! :) I already did produce a "Chore" section for my own changelog entry, but I assume that's not what you meant?

**Review by electricbrick42 — APPROVED** [review]

**Pull request merged**
