### PR TITLE
Bug/679/too many attributs in downloads

### LINKED ISSUE #679: Bug: Exported cc.json include data that is not supposed to be there
# Bug

## Expected Behavior

* The node of `"type": "Folder"` has empty `"attributes": { }`
* The node of `"type": "File"` does not have the attribute unary
* The node of `"type": "File"` does not have the `"origin": "sample1.cc.json"`

The visualization is not supposed to modify the `"nodes": []` or `"edges": []`. These are generated by the analysis. More specifically the problems are:

* A folder is not supposed to have any attributes. The Visualization is supposed to either sum or average the "file"s inside a "folder" but should not store these values in the cc.json.
* The unary attribute is a virtual attribute that is 1 for each "file". It's not supposed to be in the cc.json.
* The origin is very useful to differentiate in *Multiple Mode* where the file came from. It's weird to have it when I opened the file in *Single Mode*. 

Now for the bigger question: If I had openend multiple files in *Multiple Mode* should the "origin" be there for each "file"? I don't think it should. Currently the download button in *Multiple Mode* can be used to merge files but that was never the intention of *Multiple Mode. Merging files is supposed to be done by analysis and the merge filter. I think **we should disable the download** button for *Multiple* and *Delta Mode* because it's unclear what the resulting file will contain.

## Actual Behavior

When I save a cc.json from the visualization it includes data it's not supposed to include:

* The node of `"type": "Folder"` has `"attributes": { "unary": 4, "avgCommits": 146, "rloc": 600, ... }`
* The node of `"type": "File"` has this `"attributes": { "unary": 4 }`
* The node of `"type": "File"` has this `"origin": "sample1.cc.json"`

## Steps to Reproduce the Problem

  1. Open [CodeCharta with mini-map](https://maibornwolff.github.io/codecharta/visualization/app/index.html)
  2. Press the download button
  3. Press save

## Specifications

  - Version: 1.32.0
  - Platform: Web
  - Subsystem: Visualization
  - Browser: Firefox

### PR DESCRIPTION
**Pull request by alexhunziker**
# Removed attributes from downloaded files that should not be there

closes #679

## Description

- Removed attributes from downloaded files that should not be there
- Downloaded Files are no longer formatted

This fix may also affect #731 and #730

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by NearW** [comment]
@alexhunziker I don't really understand how to reproduce #730 
Can you check both #730 and #731 ? If one of them got fixed by this, just edit the changelog on master.

**Comment by alexhunziker** [comment]
@NearW use these maps to test #730 
[cc_downloaded.zip](https://github.com/MaibornWolff/codecharta/files/3824200/cc_downloaded.zip)

However, if you prefer me doing it, I can also do it (during the next few days)

**Comment by NearW** [comment]
This bug still exists with the provided cc.jsons, but in order to check if that bug only occurs with decorated maps being exported and then imported again, we need the non-exported version of the cc.json.

**Comment by alexhunziker** [comment]
Well these are maps that I just downloaded form our demo page, so I don't have them from the analysis... I did just test it, and I think #730 is not fixed by this, but i will try it again with two freshly downloaded maps (which we can do as soon as this is released)

**Pull request merged**
