### PR TITLE
 Implement 3MF export for multi-color 3D printing of maps (supercedes #3616)

### PR DESCRIPTION
**Pull request by olexs**
*this PR is a copy of #3616 from a local branch instead of fork*

# Implement 3MF export for multi-color 3D printing of maps

## Description

This PR implements a 3MF export in addition to the already existing STL export. This allows to print CodeCharta maps on multi-material printers like the BambuLabs machines or the Prusa XL in multiple colors. 

Additionally, the printed map now includes a MW logo, a custom text line, an optional project logo, and a reverse side with a legend of included metrics and their values.

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
- [x] Changes have been manually tested
- [x] All TODOs related to this PR have been closed
- [x] There are automated tests for newly written code and bug fixes
- [x] All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
- [ ] Documentation (GH-pages, analysis/visualization READMEs, parser READMEs, --help, etc.) has been updated (almost always necessary except for bug fixes)
- [x] CHANGELOG.md has been updated

## Screenshots
Screenshot 2024-05-14 at 17 17 58

IMG_0331
IMG_0325

### CODE REVIEW

**Comment by olexs** [comment]
wat? warum closed?

**Comment by BridgeAR** [comment]
My guess is it was by accident

**Comment by BridgeAR** [comment]
The branch has a couple of conflicts at the moment that would have to be resolved, though.

**Comment by phanlezz** [comment]
We decided to not fix the issue with the layer height in the folders, because usually the slicer can do it better.

**Review by IhsenBouallegue — APPROVED** [review]

**Pull request merged**
