### PR TITLE
Feature/682/improve docs

### LINKED ISSUE #682: Improve Docs
# Feature request

Let's improve our README as well as the user and developer documentation. We should also move the user and dev documentation all to gh-pages or move it all to the wiki. All visual doc should use draw.io because we can visualize our workflow with flowcharts in which the nodes have links to our various importers.

* Github-pages can be visually customized (custom header/footer/whatever), probably exported as pdf and provide possibilities like multi-column layouts where images are directly next to the text. Also we can link to source code directly and probably verify it's all there.
* The wiki has these benefits ...

See also #558. Also #673

### PR DESCRIPTION
**Pull request by Richargh**
# Improve Docs

closes #682 

## Description

Significantly improves docs and moves all wiki pages to the jekyll folders. The [Readme](https://github.com/MaibornWolff/codecharta/blob/feature/682/improve-docs/gh-pages/README.md) explains how to view the docs locally.

This PR does not move all importer Readmes to the docs although that would be a great goal for a future issue. This PR also does not change the Readme but that is also a good idea for future issues.

Another slight caveat: it might be that some links only work locally. I have no way to check this beforehand. In the past it's been easy to fix however.

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
I just had a first look at all the `.md` files, which you wrote for our CC docs! Thats a pretty cool and extensive introduction to CC. Thanks @Richargh!
- I just run the documentation locally and slightly updated the README.md where it lists the steps to run on a local machine
- While I am quite sure the content of the docs is a lot more organised than in our wiki, I got some questions and improvements regarding the design:
- What do we do with our Readme's inside the project? Do we gonna have duplicated Readme content?
- I am not really convinced by the design yet. I would decrease the font size and make the background light-grey or white.

**Comment by Richargh** [comment]
> What do we do with our Readme's inside the project? Do we gonna have duplicated Readme content?

As far as I know we have the [main README](https://github.com/MaibornWolff/codecharta), several README's for the importers, one for the visualization, one for the analysis and one for the gh-pages. Changing these is not the point of this branch/PR. 

What I thought of as next steps was: 

1. the point of the main README is to get developers interested in CC. So the contents should be limited to: Screenshot, a short text how CC can help him, 5-min Java quick-start tutorial, link to the docs, link to contributing link to "New to Code?". 
2. The importer READMEs have information relevant to our users. What parameters to use for example. Let's move their content to the gh-pages.
3. Leave basic developer relevant information in the visualization README. Stuff like `npm serve`. Then reference the gh-pages docs for further inquiry.
4. Leave basic developer relevant information in the analysis README. Stuff like `./gradlew build`. Then reference the gh-pages docs for further inquiry.
5. gh-pages Readme that tells you how to start Jekyll and modify the docs. Leave that where it is.

These ideas are up for debate though. My intent is to move as much as is useful into the open, so peoople can easily find it through our new search. That's why the gh-pages also has a "News" section where you can share whatever you want to share :)

> I am not really convinced by the design yet. I would decrease the font size and make the background light-grey or white.

Changing the design is possible. The docs use minimal mistakes and you can easily change the [configuration](https://mmistakes.github.io/minimal-mistakes/docs/configuration/) in the `_config.yml`, restart Jekyll and look at the results. Minimal mistakes provides several skins that might just do what you want to do. For example, the current skin is called [dark](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#dark-skin-dark) and that's just a one-line change in `minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"`. 

If you want something more drastic you can even [change the stylesheets](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/) or completely replace them. Anything here that you are interested in?

**Comment by alschmut** [comment]
Thank @Richargh i totally agree with all your mentioned points (: good documentation is an ongoing process and I am excited to move our user documentation to the gh-pages. Therefore with or without design changes, I am fine with presenting the new documentation.

**Comment by NearW** [comment]
Future issues after merging this:
- Adapt release script, so that it automatically adds a new entry in _posts/release with the patch notes
- add favicon `ERROR `/favicon.ico' not found.`

**step-by-step.md**
- `./ccsh sonarimport [sonar-server-url][project-id]`, explain what the url and what the project-id is, because url is only the host-adress and project-id is actually the project-key found on the page (we should give a hint to find this information in the sonarimport README and update it there)
- 

General feedback:
- I don't think the how-to's should be considered "news", rather have an own page for each release, ADR and how-to (guides), instead of bundling them in a category page

**Pull request merged**
