### PR TITLE
Feature/adapt-file-extension-bar-height

### PR DESCRIPTION
**Pull request by alschmut**
# Feature/adapt-file-extension-bar-height

## Description

When using the Chrome Browser, then the fileExtensionBar had a small unwanted white margin-bottom. This PR:
- Adjust fileExtensionBar height
- Remove the blue outline when focusing a fileExtensionBar-section
- Move the fileExtensionBar-detailsText up by 1px

Before
image

After
image

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [ ] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by NearW** [comment]
Why did you move the text up by one pixel? Looks like it's one pixel too high.

I would consider this a bug fix and therefore add it to the changelog.

**Comment by alschmut** [comment]
> Why did you move the text up by one pixel? Looks like it's one pixel too high.
> 
> I would consider this a bug fix and therefore add it to the changelog.

In Chrome-for-Mac the fileExtensionBar-detailsText was quite low (almost on the lower border).. Thats why. In Safari its a bit higher but still good in my opinion.

**Comment by alexhunziker** [comment]
Just posting how it looks on Windows (Chrome on the left, Firefox on the right):

Before (current Master):
FEB_old

After:
FEB_new

As you can see there is not too much of a difference, both look generally fine in my opinion. However i noticed that the file extensions within the bar are not centered (neither on master nor with the current state), which they probably should.

**Comment by alschmut** [comment]
@NearW @alexhunziker I just realised, that you are talking about the visible extensions inside the coloured section. Actually I changed the 1 pixel for the details section text underneath, but it looks like there is some CSS problem. I would probably rather undo the 1 pixel change, as it doesn't look as good anymore on chrome/firefox

> file extensions within the bar

what is within the bar? the details section underneath? vertically centred?

**Comment by alschmut** [comment]
Apparently the text inside the coloured sections didn't even change position. But if everybody agrees on the following two screenshots, where I lowered the coloured-section text a bit, we should merge this PR.

Chrome for Mac
image

Safari for Mac
image

**Pull request merged**
