### PR TITLE
Fix/3456/update mcc naming

### PR DESCRIPTION
**Pull request by Nereboss**
# Update MCC naming

Closes: #3456 

## Description

Temporarily adds 'formerly mcc' to the no longer renamed sonar complexity 

## Definition of Done

A PR is only ready for merge once all the following acceptance criteria are fulfilled:
- [x] Changes have been manually tested
- [x] All TODOs related to this PR have been closed
- [x] There are automated tests for newly written code and bug fixes
- [x] All bugs discovered while working on this PR have been submitted as issues (if not already an open issue)
- [x] Documentation (GH-pages, analysis/visualization READMEs, parser READMEs, --help, etc.) has been updated (almost always necessary except for bug fixes)
- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by phanlezz** [comment]
I rebased the branch to include the main changes

**Comment by phanlezz** [comment]
I did some testing and here are some points that I found. We should evaluate if those changes are acceptable:

- the current metric of the web demo can't be found, uses `sonar_cognitive_complexity` in local testing -> adjust link
- "Metric Templates" are not applicable anymore (contain mcc)
- "Suspicious Metrics" - MCC does not get detected as a preset
- Attribute Descriptor Title for the sonar import still state "Maximum ...". We should change that.

**Comment by Nereboss** [comment]
I think all these points should be addressed before merging this issue.

i further found that we include other metrics that talk about mcc (the sourceMonitor has max_function_mcc and average_function_mcc) that should be changed as well here.

**Comment by Nereboss** [comment]
All the previously found issues should be resolved. Additionally, the metrics "complexity" and "sonar_complexity" will include (formerly mcc) in their display name in the search (and are also findable my searching for mcc).

**Review by phanlezz — APPROVED** [review]
LGTM

**Pull request merged**
