### PR TITLE
Feature/525/move file settings

### LINKED ISSUE #525: Move File Settings to File Bar
# Feature request

Let's incrementally change our UI. First stop, move the file bar to above the metrics, so it takes on even more of a global spot. See attached screenshot.

### PR DESCRIPTION
**Pull request by alexhunziker**
# Move File Settings to File Setting Bar

closes #525 

## Description

- Move file Settings from Ribbon bar to separate File Setting Bar
- Redesign Render State Selector as a multi switch button
- Rename revisionChooser to fileSettingBar

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alexhunziker** [comment]
I am fine with FileBar or FileSettingsBar as well, FileStateBar might be too narrow since we also have the open/save components nested inside there.

**Comment by alschmut** [comment]
When I click (in Safari) on any of the tab buttons, the text goes down for a bit. On my Chrome on Mac it works..

**Comment by Richargh** [comment]
> When I click (in Safari) on any of the tab buttons, the text goes down for a bit. 

Is it only when clicking and no difference for hover? That must be margin/padding issue right?

**Comment by alschmut** [comment]
> Is it only when clicking and no difference for hover? That must be margin/padding issue right?

Yea, only when I click

**Comment by alexhunziker** [comment]
Would you be fine with filePanel as a name for the component? 

> When I click (in Safari) on any of the tab buttons, the text goes down for a bit. 

Can't reproduce it on my System... I will put margin and padding to 0 for :active of the button, then you can check if that solves the problem.

**Comment by alschmut** [comment]
> I will put margin and padding to 0 for :active of the button, then you can check if that solves the problem.

Awesome, it works 👍 But I just found another visual bug. When clicking the import or download button icon(!) it moves to the left upper corner of the button (Safari and Chrome for Mac)

**Comment by alexhunziker** [comment]
please try again, i applied the same trick; setting margin and padding of :active manually

**Comment by alschmut** [comment]
> please try again, i applied the same trick; setting margin and padding of :active manually

Yes thats it 👍 I gonna merge the branch, when travis is ready

**Pull request merged**
