### PR TITLE
Add codecharta logo

### PR DESCRIPTION
**Pull request by Christian-Eberhard**
# Adding the codecharta logo

Closes: #1881 

## Description

Adds the codecharta logo to the bottom left side of the page

## Screenshots or gifs
Logo

### CODE REVIEW

**Review by BridgeAR — CHANGES_REQUESTED** [review]
Let's have another round to improve the look and feel :-)

**Comment by BridgeAR** [comment]
Let's try to move the `MaibornWolff` part below the CodeCharta Logo and remove the `"Mensch ^ IT"` part. Reduce the `MaibornWolff` size and write `by MaibornWolff`.
The version could also be written in the same font as CodeCharta is in the Logo and reduced in size.

**Comment by ce-bo** [comment]
@BridgeAR Are any questions open or can we move it back to Backlog?

**Comment by IhsenBouallegue** [comment]
This pull request seems to be stale. Would be nice if we can close it and refer to newer PRs/Issues

**Pull request closed without merging**
